backend:
  name: github
  repo: sksatyatools/sksatyatools.github.io
  branch: main

media_folder: "images"
public_folder: "/images"

collections:
  - name: "articles"
    label: "Articles"
    folder: ""
    create: true
    slug: "{{slug}}"
    extension: "html"
    format: "frontmatter"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Content", name: "body", widget: "markdown"}
